export const CATEGORIES = {
  AUTOMOTIVE: "Automotive & Motorbike",
  ELECTRONIC_ACCESSORIES: "Electronic Accessories",
  ELECTRONIC_DEVICES: "Electronic Devices",
  GROCERIES_PETS: "Groceries & Pets",
  HEALTH_BEAUTY: "Health & Beauty",
  HOME_LIFESTYLE: "Home & Lifestyle",
  MENS_FASHION: "Men's Fashion",
  MOTHER_BABY: "Mother & Baby",
  SPORTS_OUTDOOR: "Sports & Outdoor",
  TV_HOME_APPLIANCES: "TV & Home Appliances",
  WATCHES_BAGS_JEWELLERY: "Watches, Bags & Jewellery",
  WOMENS_FASHION: "Women's Fashion",
} as const;

export const SUBCATEGORIES = {
  ACCESSORIES: "Accessories",
  AIR_CONDITIONER: "Air Conditioner",
  AUTOMOTIVE: "Automotive",
  BABY_TODDLER_TOYS: "Baby & Toddler Toys",
  BABY_GEAR: "Baby Gear",
  BABY_PERSONAL_CARE: "Baby Personal Care",
  BATH: "Bath",
  BATH_BODY: "Bath & Body",
  BEAUTY_TOOLS: "Beauty Tools",
  BEDDING: "Bedding",
  BEDS: "Beds",
  BEVERAGES: "Beverages",
  BOYS_ACCESSORIES: "Boy's Accessories",
  BOYS_CLOTHING: "Boy's Clothing",
  BOYS_SHOES: "Boy's Shoes",
  BRAS_PANTIES_LINGERIE: "Bras, Panties & Lingerie",
  BREAKFAST_CHOCO_SNACKS: "Breakfast, Choco & Snacks",
  CAMERA_ACCESSORIES: "Camera Accessories",
  CAMERAS_DRONES: "Cameras & Drones",
  CAT: "Cat",
  CHARGERS_CABLES: "Chargers & Cables",
  CLOTHING_ACCESSORIES: "Clothing & Accessories",
  COMPUTER_ACCESSORIES: "Computer Accessories",
  COMPUTER_COMPONENTS: "Computer Components",
  CONSOLES: "Consoles",
  CONTROLLERS: "Controllers",
  COOKWARE: "Cookware",
  COOLING_HEATING: "Cooling & Heating",
  DARAZ_LIKE_NEW: "Daraz Like New",
  DECOR: "Decor",
  DESKTOPS: "Desktops",
  DIAPERING_POTTY: "Diapering & Potty",
  DOG: "Dog",
  DRESSES_SKIRTS: "Dresses & Skirts",
  EXERCISE_FITNESS: "Exercise & Fitness",
  FEATURE_PHONES: "Feature Phones",
  FEEDING: "Feeding",
  FISH: "Fish",
  FITNESS_GADGETS: "Fitness Gadgets",
  FOOD_STAPLES: "Food Staples",
  FRAGRANCES: "Fragrances",
  FROZEN_FOOD: "Frozen Food",
  FURNITURE: "Furniture",
  GAMING_ACCESSORIES: "Gaming Accessories",
  GAMING_CONSOLES: "Gaming Consoles",
  GENERATOR_UPS_SOLAR: "Generator, UPS & Solar",
  GIRLS_CLOTHING: "Girls Clothing",
  GIRLS_SHOES: "Girls Shoes",
  HAIR_CARE: "Hair Care",
  HEADPHONES_HEADSETS: "Headphones & Headsets",
  HOME_AUDIO_THEATER: "Home Audio & Theater",
  INNER_WEAR: "Inner Wear",
  IRONS_GARMENT_CARE: "Irons & Garment Care",
  KIDS_WATCHES: "Kid's Watches",
  KITCHEN_APPLIANCES: "Kitchen Appliances",
  KURTAS_SHALWAR_KAMEEZ: "Kurtas & Shalwar Kameez",
  LANDLINE_PHONES: "Landline Phones",
  LAPTOP_ACCESSORIES: "Laptop Accessories",
  LAPTOP_BAGS: "Laptop Bags",
  LAPTOPS: "Laptops",
  LAUNDRY_CLEANING: "Laundry & Cleaning",
  LAUNDRY_HOUSEHOLD: "Laundry & Household",
  LIGHTING: "Lighting",
  LOADERS_RICKSHAW: "Loaders & Rickshaw",
  LUGGAGE_SUITCASE: "Luggage & Suitcase",
  MAKEUP: "Makeup",
  MATERNITY_CARE: "Maternity Care",
  MEDIA_MUSIC_BOOKS: "Media, Music & Books",
  MEDICAL_SUPPLIES: "Medical Supplies",
  MENS_CARE: "Men's Care",
  MENS_WATCHES: "Men's Watches",
  MENS_BAGS: "Mens Bags",
  MENS_JEWELLERY: "Mens Jewellery",
  MILK_FORMULA_BABY_FOOD: "Milk Formula & Baby Food",
  MOBILE_ACCESSORIES: "Mobile Accessories",
  MONITORS: "Monitors",
  MONITORS_ACCESSORIES: "Monitors & Accessories",
  MOTORCYCLE: "Motorcycle",
  MUSLIM_WEAR: "Muslim Wear",
  NETWORK_COMPONENTS: "Network Components",
  NURSERY: "Nursery",
  OUTDOOR_RECREATION: "Outdoor Recreation",
  PANTRY: "Pantry",
  PANTS_JEANS: "Pants & Jeans",
  PANTS_JEANS_LEGGINGS: "Pants, Jeans & Leggings",
  PERSONAL_CARE: "Personal Care",
  PHONE_CASE: "Phone Case",
  PORTABLE_SPEAKERS: "Portable Speakers",
  POWER_BANKS: "Power Banks",
  PRINTERS: "Printers",
  PROJECTORS_PLAYERS: "Projectors & Players",
  RACKET_SPORTS: "Racket Sports",
  REFRIGERATORS_FREEZERS: "Refrigerators & Freezers",
  REMOTE_CONTROL_VEHICLES: "Remote Control & Vehicles",
  SECURITY_CAMERAS: "Security Cameras",
  SEXUAL_WELLNESS: "Sexual Wellness",
  SHIRTS_POLO: "Shirts & Polo",
  SHOES: "Shoes",
  SHOES_CLOTHING: "Shoes & Clothing",
  SHORTS_JOGGERS_SWEATS: "Shorts, Joggers & Sweats",
  SKIN_CARE: "Skin Care",
  SKINCARE: "Skincare",
  SLEEPWEAR_INNERWEAR: "Sleepwear & Innerwear",
  SMART_PHONES: "Smart Phones",
  SMART_WATCHES: "Smart Watches",
  SNACKS: "Snacks",
  SPORTS_OUTDOOR_PLAY: "Sports & Outdoor Play",
  SPORTS_ACCESSORIES: "Sports Accessories",
  STATIONERY_CRAFT: "Stationery & Craft",
  STORAGE: "Storage",
  STUDY_TABLE: "Study Table",
  SUNGLASSES_EYEWEAR: "Sunglasses & Eyewear",
  SUPPLEMENTS: "Supplements",
  TSHIRTS_TANKS: "T-Shirts & Tanks",
  TV_ACCESSORIES: "TV Accessories",
  TEAM_SPORTS: "Team Sports",
  TELEVISIONS: "Televisions",
  TOOLS_DIY_OUTDOOR: "Tools, DIY & Outdoor",
  TOYS_GAMES: "Toys & Games",
  UNSTITCHED_FABRIC: "Unstitched Fabric",
  VACUUMS_FLOOR_CARE: "Vacuums & Floor Care",
  WARDROBES: "Wardrobes",
  WASHING_MACHINE: "Washing Machine",
  WEARABLE: "Wearable",
  WINTER_CLOTHING: "Winter Clothing",
  WOMENS_ACCESSORIES: "Women's Accessories",
  WOMENS_WATCHES: "Women's Watches",
  WOMENS_BAGS: "Womens Bags",
  WOMENS_JEWELLERY: "Womens Jewellery",
} as const;

export type CategoryValue = typeof CATEGORIES[keyof typeof CATEGORIES];
export type SubCategoryValue = typeof SUBCATEGORIES[keyof typeof SUBCATEGORIES];